POST http://localhost:8080/orders/addOrder
Content-Type: application/json

{
  "orderItems": [
    {
      "book": {
        "id": 1,
        "title": "Book Title",
        "author": "Book Author",
        "price": 19.99
      },
      "quantity": 2,
      "price": 39.98
    },
    {
      "book": {
        "id": 2,
        "title": "Another Book Title",
        "author": "Another Book Author",
        "price": 29.99
      },
      "quantity": 1,
      "price": 29.99
    }
  ]
}



