POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "street_number": 123,
  "street_name": "Main Street",
  "phone_number": 555123456,
  "postal_code": 90210,
  "province": "California",
  "role": "Admin"
}
